---
# key-copying tasks for ansible-role-ssh-keys.

- name: Isolate key filename.
  set_fact:
    ssh_key_filename: "{{ ssh_key.src | basename }}"

- name: Copy key {{ ssh_key_filename }}  into place.
  copy:
    src: "{{ ssh_key.src }}"
    dest: "{{ ssh_ssh_dir }}/{{ ssh_key_filename }}"
    owner: "{{ ssh_ssh_dir_owner }}"
    group: "{{ ssh_ssh_dir_group }}"
    # Set a safe default mode in case the user has not set one.
    mode: "{{ ssh_key.mode | default(((ssh_key_filename | splitext)[1] == '.pub') | ternary('0644', '0600')) }}"
  no_log: true
