---
- name: Converge
  hosts: all
  vars:
    # Role vars.
    ssh_user: "molecule"
    ssh_ssh_keys:
      - src: "files/keys/id_rsa"
      - src: "files/keys/id_rsa.pub"
    ssh_authorized_keys:
      - "files/keys/id_rsa.pub"
  roles:
    - role: ansible-role-ssh-keys
