---
dependency:
  name: galaxy
lint: |
  yamllint -d "{ignore: .venv}" .
  ansible-lint defaults files meta molecule tasks
  flake8 molecule
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu1804-ansible
    command: ${MOLECULE_DOCKER_COMMAND:-""}
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
provisioner:
  name: ansible
verifier:
  name: testinfra
